### ISSUE TITLE
/deploy/内のファイルを更新したい（不要なら削除したい）

### ISSUE THREAD

**Issue by naruwo-github** [sugar-cat7/isucon-tool#10]
ご意見求む

**Comment by Haya372** [comment]
結局使わなかったし、多分使わないので消していいと思います

**Comment by sugar-cat7** [comment]
同じく良い気がします！今年も中盤1人1instanceで実験するとかありそうですし👀

**Comment by naruwo-github** [comment]
反応ありがとう！

アンチパターンだけど）下記PRに含めてしまっていいかい？
https://github.com/sugar-cat7/isucon-tool/pull/9
