### ISSUE TITLE
shellコマンドの効率化: alias設定

### ISSUE THREAD

**Issue by naruwo-github** [sugar-cat7/isucon-tool#8]
ターミナルに色付けしたり、エイリアスを活用したい。
（そのためのツールを入れたい。Figとかなんかあった気がする、、、）

そのため、よく実行するコマンドや面倒な入力があれば、ここで議論したい。
（ubuntu, isucon, rootの３つのユーザで共通化できると理想だが、isuconユーザを一番使用するので、isuconユーザのみの設定で良い。）

**Comment by naruwo-github** [comment]
Git
- git: g
- git add: ga
- git commit: gc
- git push: gp (pullはショートカットにしない。適当。

**Comment by Haya372** [comment]
エイリアスとかは個人個人で差がありそうなのでこーゆーので各自設定するとかがいいと思ったのですがどうでしょう？
https://qiita.com/ikuwow/items/ba4ca57fd67c06fd1b19

**Comment by sugar-cat7** [comment]
sshrc知らなかった👀
benchとか以外のisuconでしか使わない系以外のやつはあんまり合わせる必要なさそうな気がするでsshrcとかで良さそうな気します🙆

**Comment by naruwo-github** [comment]
sshrc知らなかった！
ありがとう、賛成です🙋

**Comment by naruwo-github** [comment]
としきの言う色付けは欲しいね
`isucon-tool/scripts/setup.sh`でインストールしたいなあ

oh-my-bash/zsh, starshipくらいしか思いつかないけど、どちらも軽くはないなあ。

**Comment by Haya372** [comment]
色つけるだけでいいならzshrcにPROMPTの設定書くだけでいいんじゃないですか？
https://qiita.com/mollifier/items/40d57e1da1b325903659

補完とか別の機能も欲しいって感じですかね？

**Comment by naruwo-github** [comment]
ありがとう。色付けだけならそうだね👍
なんならコマンドごとに色付けオプションもあるし。

> 補完とか別の機能も欲しいって感じですかね？

自分はその認識で、いろんな便利機能もありつつ処理も重くなりづらい中庸を取れるものがないかなあと探していまする👀
